apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
      version: v1
  template:
    metadata:
      labels:
        app: flask
        version: v1
    spec:
      containers:
      - name: flask
        image: kunchalavikram/deployment_strategies_demo:v1
        ports:
        - name: http
          containerPort: 5000
