apiVersion: v1
kind: Pod
metadata:
  name: flask
  labels:
    app: flask2
spec:
  containers:
  - name: flask
    image: kunchalavikram/deployment_strategies_demo:v2
    ports:
    - name: http
      containerPort: 5000
