apiVersion: apps/v1
kind: Deployment
metadata:
  name: downwardapi-deployment
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: downwardapi
  template:
    metadata:
      labels:
        app: downwardapi
      annotations:
        build: four
    spec:
      containers:
      - name: client-container
        image: registry.k8s.io/busybox
        command: ["sh", "-c"]
        args:
        - |
          if [[ -e /etc/podinfo/annotations ]]; then
            echo -en '\n\n'; cat /etc/podinfo/annotations;
          fi;
          mkfifo /tmp/pipe && cat /tmp/pipe 
        volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
      volumes:
      - name: podinfo
        downwardAPI:
          items:
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations


