# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
#   labels:
#     app: nginx
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       annotations:
#         imageregistry: "2222"
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:1.14.2
#         env:
#         - name: GREET
#           value: "hello2"
#         ports:
#         - containerPort: 80
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: annotations-demo
#   annotations:
#     imageregistry: "2"
# spec:
#   containers:
#   - name: nginx
#     image: nginx:1.14.2
#     ports:
#     - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: downwardapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: downwardapi
  template:
    metadata:
      labels:
        app: downwardapi
      annotations:
        build: two
        sha: two
    spec:
      containers:
      - name: client-container
        image: registry.k8s.io/busybox
        command: ["sh", "-c"]
        args:
        - |
          if [[ -e /etc/podinfo/annotations ]]; then
            echo -en '\n\n'; cat /etc/podinfo/annotations;
          fi;
          mkfifo /tmp/pipe && cat /tmp/pipe 
        volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
      volumes:
      - name: podinfo
        downwardAPI:
          items:
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations


