apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    app: flask
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 31000
  selector:
    app: flask
