apiVersion: batch/v1
kind: Job
metadata:
  name: job-demo
  annotations:
    sha: "1"
spec:
  completions: 1
  template:
    spec:
      restartPolicy: Never
      ttlSecondsAfterFinished: 100
      containers:
      - name: example
        image: python
        command:
        - python3
        - -c
        - |
          import os
          print("Hello world")
